name: methylation-env
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core
  - r-base=4.4.*
  - pandoc

  # CRAN 
  - r-optparse
  - r-yaml
  - r-data.table
  - r-dplyr
  - r-readr
  - r-stringr
  - r-ggplot2
  - r-rmarkdown
  - r-knitr
  - r-here
  - r-janitor
  - r-matrixstats
  - r-rcolorbrewer
  - r-r.utils

  # Bioconductor
  - bioconductor-limma
  - bioconductor-genefilter
  - bioconductor-biocparallel
  - bioconductor-rsamtools
  - bioconductor-minfi
  - bioconductor-missmethyl
  - bioconductor-gviz
  - bioconductor-dmrcate
  - bioconductor-minfidata
  - bioconductor-illuminaHumanMethylation450kmanifest
  - bioconductor-illuminaHumanMethylation450kanno.ilmn12.hg19
  - bioconductor-illuminaHumanMethylationepicmanifest
  - bioconductor-illuminaHumanMethylationepicanno.ilm10b4.hg19
