name: methylation-env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base=4.3
  - pandoc
  - r-biocmanager
  - r-optparse
  - r-yaml
  - r-data.table
  - r-dplyr
  - r-readr
  - r-stringr
  - r-ggplot2
  - r-rmarkdown
  - r-knitr
  - r-here
  - r-janitor
  - r-matrixstats

  # Bioconductor + deps
  - bioconductor-minfi
  - bioconductor-missmethyl
  - bioconductor-minfidata
  - bioconductor-illuminaHumanMethylation450kmanifest
  - bioconductor-illuminaHumanMethylation450kanno.ilmn12.hg19
  - bioconductor-biocparallel
  - bioconductor-rsamtools
  - r-limma
  - r-deldir
  - r-hmisc
  - r-statmod
  - r-mclust
  - r-genefilter
