name: methycleanr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core R
  - r-base>=4.3,<4.4
  - r-biocmanager
  - r-yaml
  - r-optparse
  - r-ggplot2
  - r-matrixstats
  - r-r.utils

  # Bioconductor
  - bioconductor-minfi
  - bioconductor-limma
  - bioconductor-dmrcate
  - bioconductor-missmethyl

  # 450k + EPIC manifests/annotation 
  - bioconductor-illuminahumanmethylation450kmanifest
  - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
  - bioconductor-illuminahumanmethylationepicmanifest
  - bioconductor-illuminahumanmethylationepicanno.ilm10b4.hg19
