name: methylation-env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Core R
  - r-base=4.3.*

  # CRAN 
  - r-biocmanager
  - r-optparse
  - r-yaml
  - r-data.table
  - r-tidyverse
  - r-ggplot2
  - r-readr
  - r-dplyr
  - r-stringr
  - r-glue
  - r-here
  - r-janitor
  - r-knitr
  - r-rmarkdown
  - r-matrixstats

  # Bioconductor 
  - bioconductor-minfi=1.48.*
  - bioconductor-limma=3.56.*
  - bioconductor-dmrcate=2.16.*
  - bioconductor-missmethyl=1.36.*
  - bioconductor-illuminaio
  - bioconductor-preprocesscore
  - bioconductor-biocparallel
  - bioconductor-summarizedexperiment
  - bioconductor-genomicranges
  - bioconductor-biostrings
  - bioconductor-delayedarray

  # Manifests 
  - bioconductor-illuminahumanmethylation450kmanifest
  - bioconductor-illuminahumanmethylationepicmanifest
