name: methylation-env
channels:
  - conda-forge
  - bioconda
  - defaults
channel_priority: strict

dependencies:
  - r-base=4.3.*
  - r-biocmanager
  - r-optparse
  - r-yaml
  - r-data.table
  - r-dplyr
  - r-stringr
  - r-readr
  - r-glue
  - r-here
  - r-janitor
  - r-ggplot2
  - r-rmarkdown
  - r-knitr
  - r-matrixstats
  - pandoc
  # build deps for source Bioc installs on macOS
  - pkg-config
  - cairo
  - freetype
  - harfbuzz
  - fontconfig
  - libpng
  - llvm-openmp
  - gfortran_osx-arm64  # Apple Silicon
  - gfortran_osx-64     # Intel (solver picks the right one)
