name: methylation-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - r-base=4.3.*
  - r-biocmanager
  - r-optparse
  - r-yaml
  - r-data.table
  - r-dplyr
  - r-readr
  - r-stringr
  - r-ggplot2
  - r-rmarkdown
  - r-knitr
  - r-here
  - r-janitor
  - r-matrixstats
  - pandoc
