name: methylation-env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # R core
  - r-base=4.4.*          
  - pandoc

  # CRAN 
  - r-optparse
  - r-yaml
  - r-data.table
  - r-dplyr
  - r-readr
  - r-stringr
  - r-ggplot2
  - r-rmarkdown
  - r-knitr
  - r-here
  - r-janitor
  - r-matrixstats
  - r-rcolorbrewer

  # Bioconductor 
  - bioconductor-minfi
  - bioconductor-illuminaHumanMethylation450kmanifest
  - bioconductor-illuminaHumanMethylation450kanno.ilmn12.hg19
  - bioconductor-missmethyl
  - bioconductor-minfidata
  - bioconductor-gviz
  - bioconductor-dmrcate
  - bioconductor-limma
  - bioconductor-genefilter
  - bioconductor-biocparallel
  - bioconductor-rsamtools
